name = "Christmas Modpack 2023"
author = "insert"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51af9732fa2bf2f6f5e0c176e6137e6f6fa067f9fe04c724854857a7752f040b"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
