name = "Christmas Modpack 2023"
author = "insert"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffde3b403838e0cff28d3c98dff520e7c83b899d9c03994e205e8cc113867e62"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
