name = "Christmas Modpack 2023"
author = "insert"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd69a9c644eef1bda0bbc391e6b0c572b8b0a4c41ca3847c3eed99b8614f770e"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
