name = "Christmas Modpack 2023"
author = "insert"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9087f44d0c8e687dd7331d523c28d10222a795b78a3b7b851efc591ab008902"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
