name = "Christmas Server"
author = "insert"
version = "0.8.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cd4d09ef8231edbe8dc1a78e823d52d450463881710ba6dd2538ae0bebf69d1"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.3", "1.16.4", "1.16.5"]
