name = "Christmas Server"
author = "insert"
version = "0.8.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd38953be2bf2437c270c3c98c0a45f9d2757f8769e3e6b2e953d0a216e2e45f"

[versions]
forge = "36.2.9"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.3", "1.16.4", "1.16.5"]
