name = "Christmas Modpack"
author = "insert"
version = "2022.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03b6c31d0d05b2e17a492b89db8d543003a35c48562453f063c8ea47e6896e1c"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1", "1.18.2"]
