name = "Christmas Modpack 2023"
author = "insert"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce62ab34780f26667b2ab08901327083333acd3c1623fae2d238f26e8e17321c"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
