name = "Christmas Modpack 2023"
author = "insert"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aebfbd9265395d559ec9ab4cb5eab9b7c4a7d9e25cddd4ed994e665445e8ecca"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
