name = "Christmas Modpack 2023"
author = "insert"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86467aa44dc1f742f10322cbbde92da5e0f58740d0b5f13d817569de4fb03464"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
