
#Mekanism Additions Config. This config is synced between server and client.
[additions]
	#Fuse time for Obsidian TNT.
	#Range: > 0
	obsidianTNTDelay = 100
	#Radius of the explosion of Obsidian TNT.
	#Range: 0.1 ~ 1000.0
	obsidianTNTBlastRadius = 12.0
	#Enables the voice server for Walkie Talkies.
	voiceServerEnabled = false
	#TCP port for the Voice server to listen on.
	#Range: 1 ~ 65535
	VoicePort = 36123

	#Config options regarding spawning of entities.
	[additions.spawning]

		#Config options regarding baby creeper.
		[additions.spawning.baby-creeper]
			#Enable the spawning of baby creeper. Think baby zombies.
			shouldSpawn = false
			#The multiplier for weight of baby creeper spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#The multiplier for minimum group size of baby creeper spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for maximum group size of baby creeper spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby creeper spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for max spawn cost of baby creeper spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The list of biome ids that baby creeper will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The list of structure ids that baby creeper will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby enderman.
		[additions.spawning.baby-enderman]
			#Enable the spawning of baby enderman. Think baby zombies.
			shouldSpawn = true
			#The multiplier for weight of baby enderman spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#The multiplier for minimum group size of baby enderman spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for maximum group size of baby enderman spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby enderman spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for max spawn cost of baby enderman spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The list of biome ids that baby enderman will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The list of structure ids that baby enderman will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby skeleton.
		[additions.spawning.baby-skeleton]
			#Enable the spawning of baby skeleton. Think baby zombies.
			shouldSpawn = false
			#The multiplier for weight of baby skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#The multiplier for minimum group size of baby skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for maximum group size of baby skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for max spawn cost of baby skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The list of biome ids that baby skeleton will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The list of structure ids that baby skeleton will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby stray.
		[additions.spawning.baby-stray]
			#Enable the spawning of baby stray. Think baby zombies.
			shouldSpawn = false
			#The multiplier for weight of baby stray spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#The multiplier for minimum group size of baby stray spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for maximum group size of baby stray spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby stray spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for max spawn cost of baby stray spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The list of biome ids that baby stray will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The list of structure ids that baby stray will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

		#Config options regarding baby wither skeleton.
		[additions.spawning.baby-wither-skeleton]
			#Enable the spawning of baby wither skeleton. Think baby zombies.
			shouldSpawn = false
			#The multiplier for weight of baby wither skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			weightPercentage = 0.5
			#The multiplier for minimum group size of baby wither skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			minSizePercentage = 0.5
			#The multiplier for maximum group size of baby wither skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSizePercentage = 0.5
			#The multiplier for spawn cost per entity of baby wither skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			spawnCostPerEntityPercentage = 1.0
			#The multiplier for max spawn cost of baby wither skeleton spawns, compared to the adult mob.
			#Range: 0.0 ~ 100.0
			maxSpawnCostPercentage = 1.0
			#The list of biome ids that baby wither skeleton will not spawn in even if the normal mob variant can spawn.
			biomeBlackList = []
			#The list of structure ids that baby wither skeleton will not spawn in even if the normal mob variant can spawn.
			structureBlackList = []

